version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      
      - run:
          name: Build Dependencies
          command: bundle install
      
      - run:
          name: Build Jekyll Site
          command: bundle exec jekyll build
      
      - run:
          name: Print the current time.
          command: date
